<div id="middlescreen">


</div>


<div id="middlescreen_text">

	<form name="myform" action="index.php" method="get">
	<input type="hidden" name="section" value="search">
	<table border=0 width=100% align="center">

        <tr>
                <td align="center"><input type="text" name="search_string" placeholder="Search for Events" size=20><input type="submit" class="btn btn-primary" value="SEARCH"></td>
        </tr>


	</table>
	</form>
	
	
	<center>
	<!--
	<i class="fa fa-users fa-5x"></i>
	<h1>EXPLORE THE FUN<br></h1><br>
	
	
		<br>
	<br>
	<br>
	<br>
	<br>
	<br>-->
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators 
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>


  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  
    <div class="item active">
      <img src="/img/banner1.jpg" alt="tickets">
      <div class="carousel-caption">
        
      </div> 
    </div>

    <div class="item">
      <img src="/img/banner2.jpg" alt="RSVP">
      <div class="carousel-caption">
        
      </div> 
    </div>

    <div class="item">
      <img src="/img/banner3.jpg" alt="world">
      <div class="carousel-caption">
        
      </div>
      </div> 
      
      <div class="item">
      <img src="/img/banner4.jpg" alt="apps">
      <div class="carousel-caption">
        
      </div> 
    </div>
  </div>



  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
	
	<!--<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>-->
	
	</center>

	<br>
	


	<div align="center">
	<h2>Upcoming Events</h2>
	<?=$result[2];?>
	</div>
	<br><br><br>

</div>