<?php
// $result = auto complete non array
include "include/settings.php";
include "include/mysql.php";
include "include/templates.php";
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Responsive Bootstrap Advance Admin Template</title>

    <!-- BOOTSTRAP STYLES-->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="assets/css/font-awesome.css" rel="stylesheet" />
       <!--CUSTOM BASIC STYLES-->
    <link href="assets/css/basic.css" rel="stylesheet" />
    <!--CUSTOM MAIN STYLES-->
    <link href="assets/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <script type="text/javascript" src="js/tinymce/tinymce.min.js"></script>


   <script src="jquery-ui-1.10.3/jquery-1.9.1.js"></script>
   <script src="js/bootstrap.js"></script>
   <link rel="stylesheet" href="jquery-ui-1.10.3/themes/base/jquery.ui.all.css">
   <script src="jquery-ui-1.10.3/ui/jquery.ui.core.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.widget.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.datepicker.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.menu.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.autocomplete.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.dialog.js"></script>
   <script src='https://www.google.com/recaptcha/api.js'></script>

  <script type="text/javascript" src="js/jquery.timepicker.js"></script>
  <link rel="stylesheet" type="text/css" href="css/jquery.timepicker.css" />
  <script type="text/javascript" src="js/tinymce/tinymce.min.js"></script>

  <script>
  $(function() {
    var availableTags = [
   <?=$result;?>
    ];
    $( "#search_area" ).autocomplete({
      source: availableTags,
      appendTo: "#container",
      position: { my : "right bottom", at: "right bottom" },
      //<!-- Added SELECT event -kjg //-->
      select: function (event, ui) {
        $( "#search_area" ).val(ui.item.label);
                document.getElementById('search_area').value = ui.item.label;
        redirect_page()
        },
      //<!-- END //-->
      minLength: 1
    });
  });
  </script>


<?php
if ($_GET['section'] == "page_view") {
?>
  <script type="text/javascript" src="js/jssor.slider.mini.js"></script>
  <script type="text/javascript" src="js/slider.js"></script>
  <link href="css/slider.css" rel="stylesheet">
<?php
}
?>


        <?php
        $template->tiny_init();
        ?>

   <script>
   $(function() {
      $( "#start_date"   ).datepicker({
        dateFormat: "yy-mm-dd",
        changeMonth: true,
        changeYear: true
      });
      $( "#end_date"      ).datepicker({
        dateFormat: "yy-mm-dd",
        changeMonth: true,
        changeYear: true
      });
   });

   </script>



</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.php">Ticket Pointe</a>
            </div>

            <div class="header-right">

                <!--
                <a href="message-task.html" class="btn btn-info" title="New Message"><b>30 </b><i class="fa fa-envelope-o fa-2x"></i></a>
                <a href="message-task.html" class="btn btn-primary" title="New Task"><b>40 </b><i class="fa fa-bars fa-2x"></i></a>
                <a href="login.html" class="btn btn-danger" title="Logout"><i class="fa fa-exclamation-circle fa-2x"></i></a>
                -->

            </div>
        </nav>
        <!-- /. NAV TOP  -->

