<body bgcolor="#000000" background="../../img/bg3_events.jpg">

<div id="middlescreen">
</div>

<div id="middlescreen_text">
	<br>
	<center>

	
	
	<table border=1 cols="2" width=930 bgcolor="#fefefe" cellspacing="5" cellpadding="5">
	
	<!-- COVER PIC / TITLE PLACE and TIME -->
	
	<td valign="top" width="70%" align="left">[cover pic]</td>
	<td valign="top" width="30%"align="left">
	Title<br>
	Time and Place<br>
	Countdown<br>
	</td>
	<tr></tr>
	
	<!-- PHOTO GALLERY / EVENT DESCRIPTION -->
	
	<td valign="top" width="70%" align="left">[photo gallery]</td>
	<td valign="top" width="30%"align="left">
	Event Description
	</td>
	<tr></tr>
	
	<!-- MAP / SOCIAL ICONS / "ADD TO" BUTTONS -->
	
	<td valign="top" width="70%" align="left">
		<table border=1 cols="2" width="100%" bgcolor="#dedede" cellspacing="5" cellpadding="5">
			<td valign="top" width="50%" align="left">[map]</td>
			<td valign="top" width="50%"align="left">
			[social icons]<br>
			[add to elements]<br>
			</td>
		</table>
	</td>

	<!-- TICKET INFO and PRICE OPTIONS / PURCHASE BUTTON / REGISTER FOR EVENT BUTTON -->
		
	<td valign="top" width="30%"align="left">
	[Ticket and Price info]<br>
	[Purchase] | [Register]<br>
	</td>
	<tr></tr>
	
	</table>

	
	
	</center>
</div>

