<!-- footer section -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12">

        <div class="col-md-4 col-sm-4">
        <h4>About Us</h4>
        <p><h6>Ticket Pointe provides a low cost service for Event Management with online sales and registration</h6></p>
        </div>

        <div class="col-md-4 col-sm-4">

        </div>

        <div class="col-md-4 col-sm-4">
        <h4 class="wow fadeIn" data-wow-delay="0.9s">Connect With Us</h4>
        <ul class="social-icon">
          <li><a href="https://www.instagram.com/ticketpointe/" class="fa fa-instagram wow bounceIn" data-wow-delay="0.3s"></a></li>
          <li><a href="mailto:support@ticketpointe.com" class="fa fa-envelope-o wow bounceIn" data-wow-delay="0.6s"></a></li>
        </ul>
        </div>

      </div>

      <div class="col-md-12 col-sm-12 copyright">
        <p>&copy; 2016 TICKET POINTE, LLC . All Rights Reserved | <a target="_blank" rel="nofollow" href="http://www.ticketpointe.com/terms.html">View Our Terms</a></p>
      </div>
    </div>
  </div>
</footer>


<!-- JAVASCRIPT JS FILES --> 
<script src="js/jquery.js"></script> 
<script src="js/bootstrap.min.js"></script> 
<script src="js/nivo-lightbox.min.js"></script> 
<script src="js/smoothscroll.js"></script> 
<script src="js/jquery.sticky.js"></script> 
<script src="js/jquery.parallax.js"></script> 
<script src="js/wow.min.js"></script> 
<script src="js/custom.js"></script>
</body>
</html>
