<?php
// $result = auto complete non array
include "include/settings.php";
include "include/mysql.php";
include "include/templates.php";
?>


<!DOCTYPE html>
<html lang="en">
<head>
<title>Ticket Pointe | We get the pointe, Tickets!</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords" content="">
<meta name="description" content="">


<!-- STYLESHEET CSS FILES -->
<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/animate.min.css">
<link rel="stylesheet" href="css/font-awesome.min.css">
<link rel="stylesheet" href="css/nivo-lightbox.css">
<link rel="stylesheet" href="css/nivo_themes/default/default.css">
<link rel="stylesheet" href="css/templatemo-style.css">
<link href="css/desktop.css" rel="stylesheet">

<!-- Custom -->
 <script src="jquery-ui-1.10.3/jquery-1.9.1.js"></script>
   <script src="js/bootstrap.js"></script>
   <link rel="stylesheet" href="jquery-ui-1.10.3/themes/base/jquery.ui.all.css">
   <script src="jquery-ui-1.10.3/ui/jquery.ui.core.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.widget.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.datepicker.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.menu.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.autocomplete.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.dialog.js"></script>
   <script src='https://www.google.com/recaptcha/api.js'></script>

  <script type="text/javascript" src="js/jquery.timepicker.js"></script>
  <link rel="stylesheet" type="text/css" href="css/jquery.timepicker.css" />
  <script type="text/javascript" src="js/tinymce/tinymce.min.js"></script>

  <script>
  $(function() {
    var availableTags = [
   <?=$result;?>
    ];
    $( "#search_area" ).autocomplete({
      source: availableTags,
      appendTo: "#container",
      position: { my : "right bottom", at: "right bottom" },
      //<!-- Added SELECT event -kjg //-->
      select: function (event, ui) {
        $( "#search_area" ).val(ui.item.label);
                document.getElementById('search_area').value = ui.item.label;
        redirect_page()
        },
      //<!-- END //-->
      minLength: 1
    });
  });
  </script>


<?php
if ($_GET['section'] == "page_view") {
?>
  <script type="text/javascript" src="js/jssor.slider.mini.js"></script>
  <script type="text/javascript" src="js/slider.js"></script>
  <link href="css/slider.css" rel="stylesheet">
<?php
}
?>


  <?php
  $template->tiny_init();
  ?>

   <script>
   $(function() {
      $( "#start_date"   ).datepicker({
  dateFormat: "yy-mm-dd",
  changeMonth: true,
  changeYear: true
      });
      $( "#end_date"      ).datepicker({
  dateFormat: "yy-mm-dd",
        changeMonth: true,
        changeYear: true
      });
   });


   </script>


<!--start head-->

</head>
<body data-spy="scroll" data-target=".navbar-collapse" data-offset="50">
<!-- preloader section -->
<div class="preloader">
  <div class="sk-spinner sk-spinner-rotating-plane"></div>
</div>


<!-- home section -->

<section id="home">
  <div class="container">
      <div class="row">
      <div class="col-md-12 col-sm-12">
        <h1 class="wow bounceInDown rotate">SHARE WITH</h1>
        <h1 class="wow bounce">THE WORLD</h1>
        <a href="https://www.ticketpointe.com/register" class="btn btn-default smoothScroll">GET STARTED</a></div>
    </div>
  </div>
</section>


<!-- navigation section -->
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon icon-bar"></span> <span class="icon icon-bar"></span> <span class="icon icon-bar"></span> </button>
      <a href="#" class="navbar-brand">
            <img alt="Brand" src="images/logo3.png">TICKET POINTE</a>
            
      </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#home" class="smoothScroll">HOME</a></li>
        <li><a href="#events" class="smoothScroll">EVENTS</a></li>
        <li><a href="http://www.learnmore.ticketpointe.com">LEARN MORE</a></li>
        <li><a href="https://www.ticketpointe.com/register" class="smoothScroll">REGISTER</a></li>
        <li><a href="https://www.ticketpointe.com/login" class="smoothScroll">LOGIN</a></li>
              </ul>
    </div>
  </div>
</div>


<!-- events section -->
<section id="events">
  
  <div class="container">
    <div class="row">


      <div class="col-md-offset-3 col-md-6 col-md-offset-3  col-sm-offset-2 col-sm-8 col-sm-offset-2 title">
        
        

        <h3>UPCOMING EVENTS</h3>


        
         

        
        <hr>
        <?=$result[2];?>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
      </div>
    </div>
  </div>
  
  
</section>


<!-- categories section -->
<section id="categories">
  <div class="container">
  <div class="row">
      <div class="col-md-offset-3 col-md-6 col-md-offset-3  col-sm-offset-2 col-sm-8 col-sm-offset-2 title">
        
        <h3>CATEGORIES</h3>
       </div>
   </div>
    <div class="row">
      
      <div class="col-md-12 col-sm-12">
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-paint-brush">
        </i>
          <h3>Arts</h3>
        </div>
        
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-briefcase">
        </i>
          <h3>Conferences</h3>
        </div>
        
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-link">
        </i>
          <h3>Fitness</h3>
        </div>
        
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-usd">
        </i>
          <h3>Fundraisers</h3>
        </div>
        
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-music">
        </i>
          <h3>Music</h3>
        </div>
        
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-glass">
        </i>
          <h3>Nightlife</h3>
        </div>
        
      </div>
    </div>
  
</section>