<!DOCTYPE html>
<html lang="en">
<head>
<title>Ticket Pointe | We get the pointe, Tickets!</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords" content="">
<meta name="description" content="">


<!-- STYLESHEET CSS FILES -->
<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/animate.min.css">
<link rel="stylesheet" href="css/font-awesome.min.css">
<link rel="stylesheet" href="css/nivo-lightbox.css">
<link rel="stylesheet" href="css/nivo_themes/default/default.css">
<link rel="stylesheet" href="css/templatemo-style.css">
<link href="css/desktop.css" rel="stylesheet">




<!--start head-->

</head>
<body data-spy="scroll" data-target=".navbar-collapse" data-offset="50">
<!-- preloader section -->
<div class="preloader">
  <div class="sk-spinner sk-spinner-rotating-plane"></div>
</div>


<!-- home section -->

<section id="home">
  <div class="container">
      <div class="row">
      <div class="col-md-12 col-sm-12">
        <h1 class="wow bounceInDown rotate">SHARE WITH</h1>
        <h1 class="wow bounce">THE WORLD</h1>
        <a href="https://www.ticketpointe.com/register" class="btn btn-default smoothScroll">GET STARTED</a></div>
    </div>
  </div>
</section>


<!-- navigation section -->
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon icon-bar"></span> <span class="icon icon-bar"></span> <span class="icon icon-bar"></span> </button>
      <a href="#" class="navbar-brand">
            <img alt="Brand" src="images/logo3.png">TICKET POINTE</a>
            
      </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#home" class="smoothScroll">HOME</a></li>
        <li><a href="#events" class="smoothScroll">EVENTS</a></li>
        <li><a href="http://www.learnmore.ticketpointe.com">LEARN MORE</a></li>
        <li><a href="https://www.ticketpointe.com/register" class="smoothScroll">REGISTER</a></li>
        <li><a href="https://www.ticketpointe.com/login" class="smoothScroll">LOGIN</a></li>
              </ul>
    </div>
  </div>
</div>


<!-- events section -->
<section id="events">
  
  <div class="container">
    <div class="row">


      <div class="col-md-offset-3 col-md-6 col-md-offset-3  col-sm-offset-2 col-sm-8 col-sm-offset-2 title">
        
        

        <h3>UPCOMING EVENTS</h3>


        
         

        
        