<hr>
        <?=$result[2];?>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
      </div>
    </div>
  </div>
  
  
</section>


<!-- categories section -->
<section id="categories">
  <div class="container">
  <div class="row">
      <div class="col-md-offset-3 col-md-6 col-md-offset-3  col-sm-offset-2 col-sm-8 col-sm-offset-2 title">
        
        <h3>CATEGORIES</h3>
       </div>
   </div>
    <div class="row">
      
      <div class="col-md-12 col-sm-12">
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-paint-brush">
        </i>
          <h3>Arts</h3>
        </div>
        
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-briefcase">
        </i>
          <h3>Conferences</h3>
        </div>
        
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-link">
        </i>
          <h3>Fitness</h3>
        </div>
        
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-usd">
        </i>
          <h3>Fundraisers</h3>
        </div>
        
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-music">
        </i>
          <h3>Music</h3>
        </div>
        
        <div class="col-md-4 col-sm-4 bg-red"> 
        <i class="fa fa-glass">
        </i>
          <h3>Nightlife</h3>
        </div>
        
      </div>
    </div>
  
</section>





<!-- blank section -->
<section id="blank">
  
  
</section>