<div id="middlescreen">


</div>


<div id="middlescreen_text">
	<center>

        <form name="myform" action="index.php" method="get">
        <input type="hidden" name="section" value="search">
        <table border=0 width=800>
        <tr>
                <td align="center"><input type="text" name="search_string" id="search_area" placeholder="Search for Events" size=60>&nbsp;<input type="submit" class="btn btn-primary" value="Search"></td>
        </tr>
        <tr>
                <td><div id="container"></div></td>
        </tr>

        </table>
        </form>
	<br>


	<!--<br><br><br><br>
	
	<!--<i class="fa fa-users fa-5x"></i>	-->
	<!--<h1>EXPLORE THE FUN<br>
	</h1>
	
	<br>
	<br>
	-->
	
	
	
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators 
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>


  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  
    <div class="item active">
      <img src="/img/banner1.jpg" alt="tickets">
      <div class="carousel-caption">
        
      </div> 
    </div>

    <div class="item">
      <img src="/img/banner2.jpg" alt="RSVP">
      <div class="carousel-caption">
        
      </div> 
    </div>

    <div class="item">
      <img src="/img/banner3.jpg" alt="world">
      <div class="carousel-caption">
        
      </div>
      </div> 
      
      <div class="item">
      <img src="/img/banner4.jpg" alt="apps">
      <div class="carousel-caption">
        
      </div> 
    </div>
  </div>



  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
	
	<!--<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>-->
	

	</center>
<!--<br>
<br>
<br>
<br>
<br>
<br>-->

	<div align="center">
	<h2>Upcoming Events</h2>
	<?=$result[2];?>
	<br>
	<br>
	<br>
	<br>
	<button type="button" class="btn btn-primary" onclick="document.location.href='index.php'" value="SHOW MORE">
                <br>
                <br>
                <br>
                SHOW MORE
                </button>
	</div>



</div>