<div id="middlescreen">


</div>


<div id="middlescreen_text">

	<br><br><br><br>
	<center>
	<!--<i class="fa fa-users fa-5x"></i>	-->
	<!--<h1>EXPLORE THE FUN<br>
	</h1>
	-->
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	

	<form name="myform" action="index.php" method="get">
	<input type="hidden" name="section" value="search">
	<table border=0 width=800>
	<tr>
		<td align="center"><input type="text" name="search_string" placeholder="Type in your search here" size=60>&nbsp;<input type="submit" class="btn btn-primary" value="Search"></td>
	</tr>


	</table>
	</form>

	</center>
<br>
<br>
<br>
<br>
<br>
<br>

	<div align="center">
	<h2>Upcoming Events</h2>
	<?=$result[2];?>
	</div>

</div>

