        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li>
                        <div class="user-img-div">

                            <div class="inner-text">
                                Jhon Deo Alex
                            <br />
                                <small>Last Login : 2 Weeks Ago </small>
                            </div>
                        </div>

                    </li>


                    <li>
                        <a class="active-menu" href="index.html"><i class="fa fa-dashboard "></i>My Profile</a>
                    </li>
                    <li>
                        <a href="table.html"><i class="fa fa-flash "></i>Check-In Users</a>

                    </li>
                    <li>
                        <a href="table.html"><i class="fa fa-flash "></i>Event Details</a>

                    </li>
                    <li>
                        <a href="table.html"><i class="fa fa-flash "></i>Event Design</a>

                    </li>
                    <li>
                        <a href="table.html"><i class="fa fa-flash "></i>Social</a>

                    </li>
                    <li>
                        <a href="table.html"><i class="fa fa-flash "></i>Event Settings</a>

                    </li>
                    <li>
                        <a href="table.html"><i class="fa fa-flash "></i>Create Tickets</a>

                    </li>
                    <li>
                        <a href="table.html"><i class="fa fa-flash "></i>Manage Users</a>

                    </li>
                    <li>
                        <a href="table.html"><i class="fa fa-flash "></i>Logout</a>

                    </li>

                </ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-8">
                        <h1 class="page-head-line">HQ</h1>

                    </div>
                </div>
                <!-- /. ROW  -->
                <div class="row">
                    <div class="col-md-4">
                        <div class="main-box mb-red">
                            <a href="#">
                                <i class="fa fa-bolt fa-5x"></i>
                                <h5>Event Wizard</h5>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="main-box mb-dull">
                            <a href="#">
                                <i class="fa fa-plug fa-5x"></i>
                                <h5>Download Check-In App</h5>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- /. ROW  -->

